import { AuthContextProvider } from "@/context/AuthContext";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "RutEs || Dashboard",
  description: "Generated by RutEs",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${inter.className} font-poppins`}>
        <AuthContextProvider>{children}</AuthContextProvider>
      </body>
    </html>
  );
}
